[2024-05-19 03:41:06,403] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-05-19 03:41:06,422] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-05-19 03:41:06,423] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-19 03:41:06,423] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-19 03:41:06,424] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-19 03:41:06,442] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-06-02 06:00:00+00:00
[2024-05-19 03:41:06,452] {standard_task_runner.py:52} INFO - Started process 478 to run task
[2024-05-19 03:41:06,457] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_fhvhv', 'download_dataset_task', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '5453', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_fhvhv_dag.py', '--cfg-path', '/tmp/tmpqcnm51qi', '--error-file', '/tmp/tmpv_6y_0ik']
[2024-05-19 03:41:06,463] {standard_task_runner.py:77} INFO - Job 5453: Subtask download_dataset_task
[2024-05-19 03:41:06,562] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [running]> on host 56455cb8b229
[2024-05-19 03:41:06,624] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-19 03:41:06,663] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_fhvhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2024-05-19 03:41:06,665] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-19 03:41:06,667] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2020-06.parquet > /opt/***/raw_data/fhvhvtaxi_tripdata_2020-06.parquet']
[2024-05-19 03:41:06,686] {subprocess.py:85} INFO - Output:
[2024-05-19 03:41:19,534] {subprocess.py:93} INFO - Command exited with return code 0
[2024-05-19 03:41:19,832] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_fhvhv, task_id=download_dataset_task, execution_date=20200602T060000, start_date=20240519T034106, end_date=20240519T034119
[2024-05-19 03:41:19,877] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-19 03:41:19,922] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-16 15:54:28,035] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-12-16 15:54:28,246] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-12-16 15:54:28,247] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:54:28,248] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-12-16 15:54:28,249] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-12-16 15:54:28,552] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-06-02 06:00:00+00:00
[2024-12-16 15:54:28,587] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_fhvhv', 'download_dataset_task', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '5725', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_fhvhv_dag.py', '--cfg-path', '/tmp/tmpyfbp7qpi', '--error-file', '/tmp/tmpgs5l4lk3']
[2024-12-16 15:54:28,599] {standard_task_runner.py:77} INFO - Job 5725: Subtask download_dataset_task
[2024-12-16 15:54:28,570] {standard_task_runner.py:52} INFO - Started process 224 to run task
[2024-12-16 15:54:28,951] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [running]> on host 78f99e82b508
[2024-12-16 15:54:29,994] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-12-16 15:54:30,565] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_fhvhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2024-12-16 15:54:30,575] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-16 15:54:31,469] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2020-06.parquet > /opt/***/raw_data/fhvhvtaxi_tripdata_2020-06.parquet']
[2024-12-16 15:54:32,001] {subprocess.py:85} INFO - Output:
[2024-12-16 15:54:45,330] {base_job.py:230} ERROR - LocalTaskJob heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 202, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in merge
    _resolve_conflict_map=_resolve_conflict_map,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2244, in _merge
    merged = self.query(mapper.class_).get(key[1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1018, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1135, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 286, in load_on_pk_identity
    return q.one()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3490, in one
    ret = self.one_or_none()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3459, in one_or_none
    ret = list(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3557, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3572, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2024-12-29 14:26:16,243] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-12-29 14:26:16,284] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2024-12-29 14:26:16,285] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-12-29 14:26:16,285] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-12-29 14:26:16,285] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-12-29 14:26:16,315] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-06-02 06:00:00+00:00
[2024-12-29 14:26:16,327] {standard_task_runner.py:52} INFO - Started process 111 to run task
[2024-12-29 14:26:16,346] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_fhvhv', 'download_dataset_task', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '5921', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_fhvhv_dag.py', '--cfg-path', '/tmp/tmp_ujluwuy', '--error-file', '/tmp/tmp_mw0b8a_']
[2024-12-29 14:26:16,352] {standard_task_runner.py:77} INFO - Job 5921: Subtask download_dataset_task
[2024-12-29 14:26:16,480] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [running]> on host f6575b1efae7
[2024-12-29 14:26:16,614] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-12-29 14:26:16,679] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_fhvhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2024-12-29 14:26:16,680] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-12-29 14:26:16,681] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2020-06.parquet > /opt/***/raw_data/fhvhvtaxi_tripdata_2020-06.parquet']
[2024-12-29 14:26:16,744] {subprocess.py:85} INFO - Output:
[2024-12-29 14:26:30,078] {subprocess.py:93} INFO - Command exited with return code 0
[2024-12-29 14:26:30,253] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_fhvhv, task_id=download_dataset_task, execution_date=20200602T060000, start_date=20241229T142616, end_date=20241229T142630
[2024-12-29 14:26:30,431] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-12-29 14:26:30,741] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-01 05:06:31,256] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2025-01-01 05:06:31,271] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2025-01-01 05:06:31,271] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-01-01 05:06:31,271] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2025-01-01 05:06:31,271] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-01-01 05:06:31,284] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-06-02 06:00:00+00:00
[2025-01-01 05:06:31,291] {standard_task_runner.py:52} INFO - Started process 4141 to run task
[2025-01-01 05:06:31,296] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_fhvhv', 'download_dataset_task', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '6214', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_fhvhv_dag.py', '--cfg-path', '/tmp/tmp4tplldb9', '--error-file', '/tmp/tmp77yv935l']
[2025-01-01 05:06:31,300] {standard_task_runner.py:77} INFO - Job 6214: Subtask download_dataset_task
[2025-01-01 05:06:31,375] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [running]> on host 4228b0d90dbc
[2025-01-01 05:06:31,429] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-01-01 05:06:31,458] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_fhvhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2025-01-01 05:06:31,460] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-01 05:06:31,461] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2020-06.parquet > /opt/***/raw_data/fhvhvtaxi_tripdata_2020-06.parquet']
[2025-01-01 05:06:31,477] {subprocess.py:85} INFO - Output:
[2025-01-01 05:06:44,177] {subprocess.py:93} INFO - Command exited with return code 0
[2025-01-01 05:06:44,215] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_fhvhv, task_id=download_dataset_task, execution_date=20200602T060000, start_date=20250101T050631, end_date=20250101T050644
[2025-01-01 05:06:44,279] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-01-01 05:06:44,324] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-01 11:46:35,653] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2025-01-01 11:46:35,668] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [queued]>
[2025-01-01 11:46:35,668] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2025-01-01 11:46:35,668] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2025-01-01 11:46:35,668] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2025-01-01 11:46:35,684] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2020-06-02 06:00:00+00:00
[2025-01-01 11:46:35,691] {standard_task_runner.py:52} INFO - Started process 7255 to run task
[2025-01-01 11:46:35,697] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_fhvhv', 'download_dataset_task', 'scheduled__2020-06-02T06:00:00+00:00', '--job-id', '6330', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_fhvhv_dag.py', '--cfg-path', '/tmp/tmp2hnwmqwp', '--error-file', '/tmp/tmpayw1wq4x']
[2025-01-01 11:46:35,702] {standard_task_runner.py:77} INFO - Job 6330: Subtask download_dataset_task
[2025-01-01 11:46:35,783] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_fhvhv.download_dataset_task scheduled__2020-06-02T06:00:00+00:00 [running]> on host b9549a156c09
[2025-01-01 11:46:35,832] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2025-01-01 11:46:35,859] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_fhvhv
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2020-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-06-02T06:00:00+00:00
[2025-01-01 11:46:35,861] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-01-01 11:46:35,862] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2020-06.parquet > /opt/***/raw_data/fhvhvtaxi_tripdata_2020-06.parquet']
[2025-01-01 11:46:35,878] {subprocess.py:85} INFO - Output:
[2025-01-01 11:46:52,778] {subprocess.py:93} INFO - Command exited with return code 0
[2025-01-01 11:46:52,816] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_fhvhv, task_id=download_dataset_task, execution_date=20200602T060000, start_date=20250101T114635, end_date=20250101T114652
[2025-01-01 11:46:52,878] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-01-01 11:46:52,932] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
