[2024-05-02 03:34:00,649] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:34:00,711] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:34:00,712] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:34:00,712] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-02 03:34:00,712] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:34:00,851] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-02 03:34:00,902] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '3668', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmpplq260xi', '--error-file', '/tmp/tmpvja6v9tw']
[2024-05-02 03:34:00,954] {standard_task_runner.py:77} INFO - Job 3668: Subtask download_dataset_task
[2024-05-02 03:34:00,920] {standard_task_runner.py:52} INFO - Started process 3385 to run task
[2024-05-02 03:34:01,349] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host bef445d594dc
[2024-05-02 03:34:01,600] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-02 03:34:01,751] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-02 03:34:01,753] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-02 03:34:01,753] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz | gzip -d > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv | rm /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-02 03:34:01,877] {subprocess.py:85} INFO - Output:
[2024-05-02 03:34:01,912] {subprocess.py:89} INFO - 
[2024-05-02 03:34:01,913] {subprocess.py:89} INFO - gzip: stdin: unexpected end of file
[2024-05-02 03:34:04,178] {subprocess.py:93} INFO - Command exited with return code 0
[2024-05-02 03:34:04,786] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240502T033400, end_date=20240502T033404
[2024-05-02 03:34:04,894] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-02 03:34:05,040] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-02 03:39:48,495] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:39:48,535] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:39:48,538] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:39:48,539] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-02 03:39:48,539] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:39:48,609] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-02 03:39:48,633] {standard_task_runner.py:52} INFO - Started process 3803 to run task
[2024-05-02 03:39:48,708] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '3699', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmpamisjcqn', '--error-file', '/tmp/tmp61lb3yar']
[2024-05-02 03:39:48,721] {standard_task_runner.py:77} INFO - Job 3699: Subtask download_dataset_task
[2024-05-02 03:39:48,888] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host bef445d594dc
[2024-05-02 03:39:48,972] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-02 03:39:49,054] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-02 03:39:49,056] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-02 03:39:49,057] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz | gzip -d > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv && rm /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-02 03:39:49,132] {subprocess.py:85} INFO - Output:
[2024-05-02 03:39:49,197] {subprocess.py:89} INFO - 
[2024-05-02 03:39:49,206] {subprocess.py:89} INFO - gzip: stdin: unexpected end of file
[2024-05-02 03:39:51,583] {subprocess.py:93} INFO - Command exited with return code 1
[2024-05-02 03:39:51,624] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02 03:39:51,634] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240502T033948, end_date=20240502T033951
[2024-05-02 03:39:51,879] {standard_task_runner.py:92} ERROR - Failed to execute job 3699 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02 03:39:51,897] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-02 03:39:52,344] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02 03:57:58,868] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:57:58,977] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 03:57:58,987] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:57:58,988] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-02 03:57:58,989] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 03:57:59,046] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-02 03:57:59,091] {standard_task_runner.py:52} INFO - Started process 4756 to run task
[2024-05-02 03:57:59,117] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '3713', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp0ijgs0nf', '--error-file', '/tmp/tmpq4ogjdc2']
[2024-05-02 03:57:59,163] {standard_task_runner.py:77} INFO - Job 3713: Subtask download_dataset_task
[2024-05-02 03:57:59,535] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host bef445d594dc
[2024-05-02 03:57:59,929] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-02 03:57:59,981] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-02 03:57:59,982] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-02 03:57:59,984] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz | gzip -d > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv && rm /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-02 03:58:00,004] {subprocess.py:85} INFO - Output:
[2024-05-02 03:58:00,065] {subprocess.py:89} INFO - 
[2024-05-02 03:58:00,066] {subprocess.py:89} INFO - gzip: stdin: unexpected end of file
[2024-05-02 03:58:04,987] {subprocess.py:93} INFO - Command exited with return code 1
[2024-05-02 03:58:05,031] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02 03:58:05,152] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240502T035758, end_date=20240502T035805
[2024-05-02 03:58:05,540] {standard_task_runner.py:92} ERROR - Failed to execute job 3713 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-02 03:58:05,705] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-02 03:58:05,954] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02 17:52:41,981] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 17:52:42,130] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-02 17:52:42,131] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 17:52:42,131] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-02 17:52:42,131] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-02 17:52:42,199] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-02 17:52:42,269] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '3812', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmps_6549_f', '--error-file', '/tmp/tmp2y8xgnj9']
[2024-05-02 17:52:42,301] {standard_task_runner.py:77} INFO - Job 3812: Subtask download_dataset_task
[2024-05-02 17:52:42,267] {standard_task_runner.py:52} INFO - Started process 4159 to run task
[2024-05-02 17:52:42,610] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 1ed1a38cd1e3
[2024-05-02 17:52:42,714] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-02 17:52:42,783] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-02 17:52:42,784] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-02 17:52:42,785] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-02 17:52:42,809] {subprocess.py:85} INFO - Output:
[2024-05-02 17:53:04,238] {subprocess.py:89} INFO - 
[2024-05-02 17:53:04,367] {subprocess.py:89} INFO - gzip: /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv: No space left on device
[2024-05-02 17:53:04,367] {subprocess.py:93} INFO - Command exited with return code 1
[2024-05-02 17:53:04,433] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-0[2024-05-03 08:54:26,893] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 08:54:27,041] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 08:54:27,041] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 08:54:27,042] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-05-03 08:54:27,042] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 08:54:27,159] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-03 08:54:27,197] {standard_task_runner.py:52} INFO - Started process 1445 to run task
[2024-05-03 08:54:27,239] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '3932', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp9dki4t2m', '--error-file', '/tmp/tmp8aamjzgn']
[2024-05-03 08:54:27,279] {standard_task_runner.py:77} INFO - Job 3932: Subtask download_dataset_task
[2024-05-03 08:54:27,760] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 5bfe1025092b
[2024-05-03 08:54:28,357] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-03 08:54:28,534] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-03 08:54:28,655] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-03 08:54:28,657] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-03 08:54:28,756] {subprocess.py:85} INFO - Output:
[2024-05-03 08:54:41,603] {subprocess.py:89} INFO - 
[2024-05-03 08:54:41,603] {subprocess.py:89} INFO - gzip: /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv: No space left on device
[2024-05-03 08:54:41,815] {subprocess.py:93} INFO - Command exited with return code 1
[2024-05-03 08:54:41,942] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03 08:54:42,223] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_b[2024-05-03 09:50:41,317] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 09:50:41,353] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 09:50:41,353] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 09:50:41,353] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-03 09:50:41,353] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 09:50:41,413] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-03 09:50:41,422] {standard_task_runner.py:52} INFO - Started process 663 to run task
[2024-05-03 09:50:41,447] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '4001', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp749x8j07', '--error-file', '/tmp/tmp2dyb19lv']
[2024-05-03 09:50:41,467] {standard_task_runner.py:77} INFO - Job 4001: Subtask download_dataset_task
[2024-05-03 09:50:41,641] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host b81c18b6cf72
[2024-05-03 09:50:41,824] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-03 09:50:41,901] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-03 09:50:41,903] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-03 09:50:41,904] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-03 09:50:41,995] {subprocess.py:85} INFO - Output:
[2024-05-03 09:51:01,806] {subprocess.py:89} INFO - 
[2024-05-03 09:51:01,806] {subprocess.py:89} INFO - gzip: /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv: No space left on device
[2024-05-03 09:51:02,068] {subprocess.py:93} INFO - Command exited with return code 1
[2024-05-03 09:51:02,190] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03 09:51:02,299] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240503T095041, end_date=20240503T095102
[2024-05-03 09:51:02,714] {standard_task_runner.py:92} ERROR - Failed to execute job 4001 for task download_dataset_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-03 09:51:02,800] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-05-03 09:51:03,096] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03 16:39:54,597] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 16:39:54,657] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-03 16:39:54,657] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 16:39:54,657] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-03 16:39:54,658] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-03 16:39:54,760] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-03 16:39:54,794] {standard_task_runner.py:52} INFO - Started process 326 to run task
[2024-05-03 16:39:54,834] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '4222', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp9c98_wpp', '--error-file', '/tmp/tmpf3f5xi0y']
[2024-05-03 16:39:54,888] {standard_task_runner.py:77} INFO - Job 4222: Subtask download_dataset_task
[2024-05-03 16:39:55,143] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host f0ab9bf9b587
[2024-05-03 16:39:55,394] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-03 16:39:55,534] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-03 16:39:55,535] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-03 16:39:55,536] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-03 16:39:55,569] {subprocess.py:85} INFO - Output:
[2024-05-03 16:40:46,040] {subprocess.py:93} INFO - Command exited with return code 0
[2024-05-03 16:40:46,207] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240503T163954, end_date=20240503T164046
[2024-05-03 16:40:46,384] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-03 16:40:46,624] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-05 12:01:21,657] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-05 12:01:21,716] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-05 12:01:21,717] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-05 12:01:21,717] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-05 12:01:21,717] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-05 12:01:21,782] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-05 12:01:21,812] {standard_task_runner.py:52} INFO - Started process 1028 to run task
[2024-05-05 12:01:21,869] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '4348', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp7qa3901v', '--error-file', '/tmp/tmpzjhrdzq9']
[2024-05-05 12:01:21,893] {standard_task_runner.py:77} INFO - Job 4348: Subtask download_dataset_task
[2024-05-05 12:01:22,211] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 19865117eb6d
[2024-05-05 12:01:22,332] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-05 12:01:22,406] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-05 12:01:22,406] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-05 12:01:22,407] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-05 12:01:22,539] {subprocess.py:85} INFO - Output:
[2024-05-05 12:02:13,077] {subprocess.py:93} INFO - Command exited with return code 0
[2024-05-05 12:02:13,497] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240505T120121, end_date=20240505T120213
[2024-05-05 12:02:13,861] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-05 12:02:14,267] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-06 07:40:00,172] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-06 07:40:00,313] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [queued]>
[2024-05-06 07:40:00,314] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 07:40:00,315] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2024-05-06 07:40:00,315] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-05-06 07:40:00,669] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-09-02 06:00:00+00:00
[2024-05-06 07:40:00,699] {standard_task_runner.py:52} INFO - Started process 3276 to run task
[2024-05-06 07:40:00,721] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_bigquery_yt', 'download_dataset_task', 'scheduled__2019-09-02T06:00:00+00:00', '--job-id', '4499', '--raw', '--subdir', 'DAGS_FOLDER/data_ingstion_gcs_yt_dag.py', '--cfg-path', '/tmp/tmp9hm9wgls', '--error-file', '/tmp/tmpw3ahlrae']
[2024-05-06 07:40:00,779] {standard_task_runner.py:77} INFO - Job 4499: Subtask download_dataset_task
[2024-05-06 07:40:01,420] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data_bigquery_yt.download_dataset_task scheduled__2019-09-02T06:00:00+00:00 [running]> on host 1aa5194a14e3
[2024-05-06 07:40:01,679] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-05-06 07:40:01,869] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data_bigquery_yt
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T06:00:00+00:00
[2024-05-06 07:40:01,870] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-05-06 07:40:01,871] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sSL https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-09.csv.gz > /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz && gunzip /opt/***/raw_data/yellowtaxi_tripdata_2019-09.csv.gz']
[2024-05-06 07:40:01,996] {subprocess.py:85} INFO - Output:
[2024-05-06 07:40:44,479] {subprocess.py:93} INFO - Command exited with return code 0
[2024-05-06 07:40:44,710] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ingest_data_bigquery_yt, task_id=download_dataset_task, execution_date=20190902T060000, start_date=20240506T074000, end_date=20240506T074044
[2024-05-06 07:40:45,011] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-05-06 07:40:45,333] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
