[2024-03-26 14:34:24,976] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 14:34:25,055] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 14:34:25,059] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 14:34:25,059] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 14:34:25,062] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 14:34:25,142] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2021-08-02 06:00:00+00:00
[2024-03-26 14:34:25,170] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2024-03-26 14:34:25,195] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpgpspnjmz', '--error-file', '/tmp/tmppwsxpge7']
[2024-03-26 14:34:25,196] {standard_task_runner.py:77} INFO - Job 165: Subtask ingest
[2024-03-26 14:34:25,344] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [running]> on host 55b5831905d1
[2024-03-26 14:34:25,442] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 14:34:25,499] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 14:34:25,501] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/output_2021-08.csv 2021-08-02T06:00:00+00:00
[2024-03-26 14:34:25,501] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 14:34:25,660] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2021_08 in the database...
[2024-03-26 14:34:25,661] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 38, in ingest_callable
    chunk.tpep_pickup_datetime = pd.to_datetime(chunk.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2024-03-26 14:34:25,695] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210802T060000, start_date=20240326T143424, end_date=20240326T143425
[2024-03-26 14:34:25,742] {standard_task_runner.py:92} ERROR - Failed to execute job 165 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_scipt.py", line 38, in ingest_callable
    chunk.tpep_pickup_datetime = pd.to_datetime(chunk.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2024-03-26 14:34:25,790] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-03-26 14:34:25,916] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-26 15:30:01,757] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 15:30:01,778] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [queued]>
[2024-03-26 15:30:01,779] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:30:01,780] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-03-26 15:30:01,780] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-03-26 15:30:01,796] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2021-08-02 06:00:00+00:00
[2024-03-26 15:30:01,805] {standard_task_runner.py:52} INFO - Started process 955 to run task
[2024-03-26 15:30:01,811] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'scheduled__2021-08-02T06:00:00+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpwc01v6p1', '--error-file', '/tmp/tmp58ytip48']
[2024-03-26 15:30:01,812] {standard_task_runner.py:77} INFO - Job 282: Subtask ingest
[2024-03-26 15:30:01,901] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest scheduled__2021-08-02T06:00:00+00:00 [running]> on host 153a478eba08
[2024-03-26 15:30:01,952] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-03-26 15:30:01,990] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2021-08-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-02T06:00:00+00:00
[2024-03-26 15:30:01,991] {logging_mixin.py:109} INFO - yellow_taxi_2021_08 /opt/***/output_2021-08.csv 2021-08-02T06:00:00+00:00
[2024-03-26 15:30:01,991] {logging_mixin.py:109} INFO - Starting data ingestion process...
[2024-03-26 15:30:02,043] {logging_mixin.py:109} INFO - Writing data to table yellow_taxi_2021_08 in the database...
[2024-03-26 15:30:02,064] {logging_mixin.py:109} INFO - Data ingestion complete
[2024-03-26 15:30:02,064] {logging_mixin.py:109} INFO - Data ingestion process completed in 0.07 seconds.
[2024-03-26 15:30:02,065] {python.py:175} INFO - Done. Returned value was: None
[2024-03-26 15:30:02,093] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20210802T060000, start_date=20240326T153001, end_date=20240326T153002
[2024-03-26 15:30:02,150] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-03-26 15:30:02,214] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
